#!/usr/bin/bash

# Please ensure the runner of this script has write permissions to the dir
# specified by GITOLITE_ADMIN_DIR

# Change these to match your install
GITOLITE_ADMIN_DIR="/home/git/gitolite-admin"

user="$1"
keyfile="$2"

# Create the gitolite repo
cd $GITOLITE_ADMIN_DIR
cp $keyfile keydir/$user.pub

echo "repo doc_$user" >> conf/gitolite.conf
echo "    RW+ = $user cam" >> conf/gitolite.conf

git add conf keydir
git commit -m "update repository to add $user"
git push origin master

