#!/bin/bash

PIPE_LOC="/etc/belhalla"

if [ ! -e PIPE_LOC ]; then
  echo "No pipe location found! Please see README.txt"
  exit 1
fi

BELHALLA_PIPE=$(cat PIPE_LOC)

if [ ! -e $BELHALLA_PIPE ]; then
  echo "Belhalla service not running!"
  exit 2
fi

echo "$@" > $BELHALLA_PIPE

